package com.my.core.cryptography.enums;

public enum Algorithm {
    RAIL_FENCE,
    NUMBER_KEY_MATRIX_TRANSPOSITION,
    WORD_KEY_MATRIX_TRANSPOSITION,
    WORD_KEY_COLUMN_VARIANT_MATRIX_TRANSPOSITION,
    CAESAR_CIPHER,
    VIGENERE_CIPHER,
    LFSR_GENERATOR,
    SYNCHRONOUS_STREAM,
    CIPHERTEXT_AUTOKEY,
    DES;
}
